name: 'Deploy to Tailscale Server'
description: 'Distribuisce il repository su un server Tailscale'
inputs:
  server_ip:
    description: 'IP o hostname del server'
    required: true
  ssh_user:
    description: 'Nome utente SSH'
    required: true
  ts_oauth_client_id:
    description: 'Tailscale OAuth Client ID'
    required: true
  ts_oauth_secret:
    description: 'Tailscale OAuth Secret'
    required: true
  tags:
    description: 'Tags for Tailscale'
    required: true
runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v2
    - name: Tailscale
      uses: tailscale/github-action@v2
      with:
        oauth-client-id: ${{ inputs.ts_oauth_client_id }}
        oauth-secret: ${{ inputs.ts_oauth_secret }}
        tags: ${{ inputs.tags }}
    - name: Deploy to Server
      env:
        SERVER_IP: ${{ inputs.server_ip }}
        SSH_USER: ${{ inputs.ssh_user }}
      shell: bash
      run: |
        # Verifica le variabili di connessione
        if [ -z "$SERVER_IP" ] || [ -z "$SSH_USER" ]; then
          echo "Errore: Le variabili SERVER_IP o SSH_USER non sono impostate"
          exit 1
        fi

        # Imposta i dettagli di connessione
        CONNECTION="$SSH_USER@$SERVER_IP"
        echo "Tentativo di connessione a $CONNECTION"

        # Testa la connessione SSH
        if ! ssh -o StrictHostKeyChecking=no -o ConnectTimeout=10 $CONNECTION 'echo "Connessione SSH riuscita"'; then
          echo "Errore: Impossibile stabilire la connessione SSH"
          exit 1
        fi

        # Crea un file di servizio temporaneo
        echo "[Unit]
        Description=StartUp Service for %I

        [Service]
        Type=simple
        ExecStart=/bin/bash -l -c \"%h/%i/init.sh\"
        WorkingDirectory=%h/%i
        Restart=on-failure
        RestartSec=5s
        TimeoutStopSec=30

        [Install]
        WantedBy=default.target" > service.tmp

        # Imposta il nome del repository
        REPO_NAME=$(echo "${{ github.repository }}" | cut -d "/" -f2)
        echo "Configurazione del repository: $REPO_NAME"

        # Crea la directory systemd utente e trasferisce il file di servizio
        ssh -o StrictHostKeyChecking=no $CONNECTION "mkdir -p ~/.config/systemd/user"
        scp -o StrictHostKeyChecking=no service.tmp "$CONNECTION:~/.config/systemd/user/startup-deployed@.service"
        rm service.tmp

        # Distribuisci il repository e il servizio
        ssh -o StrictHostKeyChecking=no $CONNECTION "
          set -e
          systemctl --user daemon-reload
          if [ ! -d ~/$REPO_NAME ]; then
            echo 'Clonazione del repository...'
            git clone https://github.com/${{ github.repository }} ~/$REPO_NAME
          else
            echo 'Aggiornamento del repository esistente...'
            systemctl --user stop startup-deployed@$REPO_NAME.service || true
            cd ~/$REPO_NAME
            git fetch
            git pull
          fi
          chmod +x ~/$REPO_NAME/init.sh
          systemctl --user enable --now startup-deployed@$REPO_NAME.service
          echo 'Distribuzione completata con successo'"
